EN_TO_KO = {
    "Braised lotus roots":           "연근조림",
    "Dongchimi":                     "동치미",
    "Japchae":                       "잡채",
    "Kimchi stew":                   "김치찌개",
    "Kimchi":                        "김치",
    "Korean rib":                    "갈비",
    "Korean style raw beef":         "육회",
    "Seasoned bean sprouts":         "콩나물무침",
    "Udon":                          "우동",
    "baek Kimchi":                   "백김치",
    "banquet noodles":               "잔치국수",
    "bean sprout soup":              "콩나물국",
    "beef-bone soup":                "곰탕",
    "bellflower greens":             "도라지나물",
    "bibimbap":                      "비빔밥",
    "boiled fish paste soup":        "어묵국",
    "budaejjigae":                   "부대찌개",
    "bulgogi":                       "불고기",
    "chonggak Kimchi":               "총각김치",
    "cucumber kimchi":               "오이소박이",
    "cup rice":                      "컵밥",
    "dried pollack soup":            "북어국",
    "eel":                           "장어",
    "fried rice":                    "볶음밥",
    "green onion Kimchi":            "파김치",
    "grilled mackerel":              "고등어구이",
    "janjorim":                      "장조림",
    "jeyuk bokkeum":                 "제육볶음",
    "memil soba":                    "메밀소바",
    "miso soup":                     "된장국",
    "mixed rice":                    "잡곡밥",
    "nabak Kimchi":                  "나박김치",
    "naengMyeon":                    "냉면",
    "pickled sesame leaf":           "깻잎장아찌",
    "pig hocks":                     "족발",
    "pork belly":                    "삼겹살",
    "radish Kimchi":                 "깍두기",
    "radish kimchi":                 "깍두기",
    "rice ball":                     "주먹밥",
    "rice roll":                     "김밥",
    "rice":                          "밥",
    "seasoned bean sprouts":         "콩나물무침",
    "seasoned bellflower root":      "도라지나물",
    "seasoned bracken":              "고사리나물",
    "seasoned zucchini":             "애호박볶음",
    "seaweed soup":                  "미역국",
    "seaweed":                       "미역",
    "shellfish soup":                "조개탕",
    "spicy yuke jang":               "육개장",
    "spinach greens":                "시금치나물",
    "stewed mackerel":               "고등어조림",
    "stir-fried anchovies":          "멸치볶음",
    "young radish Kimchi":           "어린무김치",
    "Tteokbokki":                    "떡볶이",
    "Sundae":                        "순대",
    "Sushi":                         "초밥",
    "Sashimi":                       "회",
    "Soy sauce crab":               "간장게장",
    "Spicy marinated crab":         "양념게장",
    "Grilled short ribs":           "LA갈비",
    "Cold soybean soup noodles":    "콩국수",
    "Spicy cold noodles":           "비빔냉면",
    "Stir-fried octopus":           "낙지볶음",
    "Spicy stir-fried chicken":     "닭갈비",
    "Chicken and ginseng soup":     "삼계탕",
    "Braised spicy chicken":        "닭볶음탕",
    "Grilled eel":                  "장어구이",
    "Grilled beef intestines":      "곱창구이",
    "Spicy fish stew":              "매운탕",
    "Boiled pork slices":           "보쌈",
    "Fermented skate":              "홍어",
    "Steamed eggs":                 "계란찜",
    "Pan-fried tofu":               "두부부침",
    "Spicy stir-fried pork":        "매운 제육볶음",
    "Mung bean pancake":            "녹두전",
    "Korean sweet pancakes":        "호떡",
    "Korean blood sausage soup":    "순댓국"
}


def translate_label(eng_label: str) -> str:
    return EN_TO_KO.get(eng_label, eng_label)